### PR TITLE
Add tests and fix enumFromTo, closes #15

### LINKED ISSUE #15: Inconsistent behavior of enumFromTo for bounded enums
With the canonical `Enum` instance for the following data type
``` purs
data T = A | B | C | D
```
I get:
``` purs
> enumFromTo A A :: Array T
[A]
> enumFromTo A B :: Array T
[A,B]
> enumFromTo A C :: Array T
[A,B,C]
> enumFromTo A D :: Array T
[A,B,C]
```

The last one returns a wrong result with the current implementation for `enumFromTo` because the unfoldr-function calls `succ D`, which short-circuits in the Maybe monad and breaks the unfoldr 'loop'.

Note: this only fails for bounded Enums

### PR DESCRIPTION
**Pull request by sharkdp**
I'm not sure if the changes to .travis.yml and package.json are fine...

### CODE REVIEW

**Comment by sharkdp** [comment]
This PR actually depends on https://github.com/purescript/purescript/pull/1963 as I'm using Eq and Ord deriving. This is why the build fails.

**Comment by garyb** [comment]
Looks great, and thanks for adding the tests. I'll leave this open until we figure out what we're doing with getting the deriving changes included.

**Comment by garyb** [comment]
Could you rebase this please?

**Comment by sharkdp** [comment]
Rebased, but cannot get this working (neither on Travis, nor locally)... I need psc 0.9.0 in order to parse the Foldable.js FFI code, but pulp 8.2.1 does not work with psc 0.9.0...

**Comment by paf31** [comment]
You have to either build Pulp 9 with psc 0.8.*, or use vanilla psc to build this, I think.

**Comment by garyb** [comment]
No problem, I'll cherry-pick this and fix up anything else that is required. Thanks!

**Comment by sharkdp** [comment]
> You have to either build Pulp 9 with psc 0.8.*, or use vanilla psc to build this, I think.

Thanks for the hint. The tests pass locally if I build everything manually with psc 0.9.0. I cannot get Pulp master working (with both psc 0.9 and 0.8)... what is the right procedure to install Pulp manually? I tried following the steps in .travis.yml ...

**Comment by garyb** [comment]
I had difficulty getting pulp to build from master too, I can't remember what I did to make it work in the end. I think there were dependency issues, perhaps a missing commit hash or something. @hdgarrood?

**Comment by hdgarrood** [comment]
Yeah, that sounds plausible. I think pulp should be updated to point at psvm master now, the PR it needed has been merged now IIRC. I can't get to a computer to address this until this weekend unfortunately.

**Comment by garyb** [comment]
No need for me to do anything, checked out locally this builds and tests successfully. Thank you!

**Pull request merged**
